/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedShopRouteImport } from './routes/_authenticated/shop'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedPlatformRouteImport } from './routes/_authenticated/platform'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedChallengesRouteImport } from './routes/_authenticated/challenges'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/app'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedPlayIndexRouteImport } from './routes/_authenticated/play.index'
import { Route as AuthenticatedPlatformIndexRouteImport } from './routes/_authenticated/platform.index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedResultsSessionIdRouteImport } from './routes/_authenticated/results.$sessionId'
import { Route as AuthenticatedQuizzesIdRouteImport } from './routes/_authenticated/quizzes.$id'
import { Route as AuthenticatedPlaySessionIdRouteImport } from './routes/_authenticated/play.$sessionId'
import { Route as AuthenticatedPlatformTeamRouteImport } from './routes/_authenticated/platform.team'
import { Route as AuthenticatedPlatformSettingsRouteImport } from './routes/_authenticated/platform.settings'
import { Route as AuthenticatedPlatformPipelineRouteImport } from './routes/_authenticated/platform.pipeline'
import { Route as AuthenticatedPlatformHealthRouteImport } from './routes/_authenticated/platform.health'
import { Route as AuthenticatedPlatformBillingRouteImport } from './routes/_authenticated/platform.billing'
import { Route as AuthenticatedInviteTokenRouteImport } from './routes/_authenticated/invite.$token'
import { Route as AuthenticatedHostSessionIdRouteImport } from './routes/_authenticated/host.$sessionId'
import { Route as AuthenticatedAdminUpgradeRouteImport } from './routes/_authenticated/admin.upgrade'
import { Route as AuthenticatedAdminMembersRouteImport } from './routes/_authenticated/admin.members'
import { Route as AuthenticatedAdminItemsRouteImport } from './routes/_authenticated/admin.items'
import { Route as AuthenticatedAdminDocumentsRouteImport } from './routes/_authenticated/admin.documents'
import { Route as AuthenticatedAdminDepartmentsRouteImport } from './routes/_authenticated/admin.departments'
import { Route as AuthenticatedAdminChallengesRouteImport } from './routes/_authenticated/admin.challenges'
import { Route as AuthenticatedAdminBanksRouteImport } from './routes/_authenticated/admin.banks'
import { Route as AuthenticatedAdminBadgesRouteImport } from './routes/_authenticated/admin.badges'
import { Route as AuthenticatedAdminAnalyticsRouteImport } from './routes/_authenticated/admin.analytics'
import { Route as AuthenticatedAdminBanksBankIdRouteImport } from './routes/_authenticated/admin.banks.$bankId'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedShopRoute = AuthenticatedShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPlatformRoute = AuthenticatedPlatformRouteImport.update({
  id: '/platform',
  path: '/platform',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedChallengesRoute = AuthenticatedChallengesRouteImport.update({
  id: '/challenges',
  path: '/challenges',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPlayIndexRoute = AuthenticatedPlayIndexRouteImport.update({
  id: '/play/',
  path: '/play/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPlatformIndexRoute =
  AuthenticatedPlatformIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedPlatformRoute,
  } as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedResultsSessionIdRoute =
  AuthenticatedResultsSessionIdRouteImport.update({
    id: '/results/$sessionId',
    path: '/results/$sessionId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedQuizzesIdRoute = AuthenticatedQuizzesIdRouteImport.update({
  id: '/quizzes/$id',
  path: '/quizzes/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPlaySessionIdRoute =
  AuthenticatedPlaySessionIdRouteImport.update({
    id: '/play/$sessionId',
    path: '/play/$sessionId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPlatformTeamRoute =
  AuthenticatedPlatformTeamRouteImport.update({
    id: '/team',
    path: '/team',
    getParentRoute: () => AuthenticatedPlatformRoute,
  } as any)
const AuthenticatedPlatformSettingsRoute =
  AuthenticatedPlatformSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedPlatformRoute,
  } as any)
const AuthenticatedPlatformPipelineRoute =
  AuthenticatedPlatformPipelineRouteImport.update({
    id: '/pipeline',
    path: '/pipeline',
    getParentRoute: () => AuthenticatedPlatformRoute,
  } as any)
const AuthenticatedPlatformHealthRoute =
  AuthenticatedPlatformHealthRouteImport.update({
    id: '/health',
    path: '/health',
    getParentRoute: () => AuthenticatedPlatformRoute,
  } as any)
const AuthenticatedPlatformBillingRoute =
  AuthenticatedPlatformBillingRouteImport.update({
    id: '/billing',
    path: '/billing',
    getParentRoute: () => AuthenticatedPlatformRoute,
  } as any)
const AuthenticatedInviteTokenRoute =
  AuthenticatedInviteTokenRouteImport.update({
    id: '/invite/$token',
    path: '/invite/$token',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedHostSessionIdRoute =
  AuthenticatedHostSessionIdRouteImport.update({
    id: '/host/$sessionId',
    path: '/host/$sessionId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminUpgradeRoute =
  AuthenticatedAdminUpgradeRouteImport.update({
    id: '/upgrade',
    path: '/upgrade',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminMembersRoute =
  AuthenticatedAdminMembersRouteImport.update({
    id: '/members',
    path: '/members',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminItemsRoute = AuthenticatedAdminItemsRouteImport.update({
  id: '/items',
  path: '/items',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminDocumentsRoute =
  AuthenticatedAdminDocumentsRouteImport.update({
    id: '/documents',
    path: '/documents',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminDepartmentsRoute =
  AuthenticatedAdminDepartmentsRouteImport.update({
    id: '/departments',
    path: '/departments',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminChallengesRoute =
  AuthenticatedAdminChallengesRouteImport.update({
    id: '/challenges',
    path: '/challenges',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminBanksRoute = AuthenticatedAdminBanksRouteImport.update({
  id: '/banks',
  path: '/banks',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminBadgesRoute =
  AuthenticatedAdminBadgesRouteImport.update({
    id: '/badges',
    path: '/badges',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAnalyticsRoute =
  AuthenticatedAdminAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminBanksBankIdRoute =
  AuthenticatedAdminBanksBankIdRouteImport.update({
    id: '/$bankId',
    path: '/$bankId',
    getParentRoute: () => AuthenticatedAdminBanksRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/app': typeof AuthenticatedAppRoute
  '/challenges': typeof AuthenticatedChallengesRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/platform': typeof AuthenticatedPlatformRouteWithChildren
  '/profile': typeof AuthenticatedProfileRoute
  '/shop': typeof AuthenticatedShopRoute
  '/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/admin/badges': typeof AuthenticatedAdminBadgesRoute
  '/admin/banks': typeof AuthenticatedAdminBanksRouteWithChildren
  '/admin/challenges': typeof AuthenticatedAdminChallengesRoute
  '/admin/departments': typeof AuthenticatedAdminDepartmentsRoute
  '/admin/documents': typeof AuthenticatedAdminDocumentsRoute
  '/admin/items': typeof AuthenticatedAdminItemsRoute
  '/admin/members': typeof AuthenticatedAdminMembersRoute
  '/admin/upgrade': typeof AuthenticatedAdminUpgradeRoute
  '/host/$sessionId': typeof AuthenticatedHostSessionIdRoute
  '/invite/$token': typeof AuthenticatedInviteTokenRoute
  '/platform/billing': typeof AuthenticatedPlatformBillingRoute
  '/platform/health': typeof AuthenticatedPlatformHealthRoute
  '/platform/pipeline': typeof AuthenticatedPlatformPipelineRoute
  '/platform/settings': typeof AuthenticatedPlatformSettingsRoute
  '/platform/team': typeof AuthenticatedPlatformTeamRoute
  '/play/$sessionId': typeof AuthenticatedPlaySessionIdRoute
  '/quizzes/$id': typeof AuthenticatedQuizzesIdRoute
  '/results/$sessionId': typeof AuthenticatedResultsSessionIdRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/platform/': typeof AuthenticatedPlatformIndexRoute
  '/play/': typeof AuthenticatedPlayIndexRoute
  '/admin/banks/$bankId': typeof AuthenticatedAdminBanksBankIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/app': typeof AuthenticatedAppRoute
  '/challenges': typeof AuthenticatedChallengesRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/shop': typeof AuthenticatedShopRoute
  '/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/admin/badges': typeof AuthenticatedAdminBadgesRoute
  '/admin/banks': typeof AuthenticatedAdminBanksRouteWithChildren
  '/admin/challenges': typeof AuthenticatedAdminChallengesRoute
  '/admin/departments': typeof AuthenticatedAdminDepartmentsRoute
  '/admin/documents': typeof AuthenticatedAdminDocumentsRoute
  '/admin/items': typeof AuthenticatedAdminItemsRoute
  '/admin/members': typeof AuthenticatedAdminMembersRoute
  '/admin/upgrade': typeof AuthenticatedAdminUpgradeRoute
  '/host/$sessionId': typeof AuthenticatedHostSessionIdRoute
  '/invite/$token': typeof AuthenticatedInviteTokenRoute
  '/platform/billing': typeof AuthenticatedPlatformBillingRoute
  '/platform/health': typeof AuthenticatedPlatformHealthRoute
  '/platform/pipeline': typeof AuthenticatedPlatformPipelineRoute
  '/platform/settings': typeof AuthenticatedPlatformSettingsRoute
  '/platform/team': typeof AuthenticatedPlatformTeamRoute
  '/play/$sessionId': typeof AuthenticatedPlaySessionIdRoute
  '/quizzes/$id': typeof AuthenticatedQuizzesIdRoute
  '/results/$sessionId': typeof AuthenticatedResultsSessionIdRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/platform': typeof AuthenticatedPlatformIndexRoute
  '/play': typeof AuthenticatedPlayIndexRoute
  '/admin/banks/$bankId': typeof AuthenticatedAdminBanksBankIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/app': typeof AuthenticatedAppRoute
  '/_authenticated/challenges': typeof AuthenticatedChallengesRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/platform': typeof AuthenticatedPlatformRouteWithChildren
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/shop': typeof AuthenticatedShopRoute
  '/_authenticated/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/_authenticated/admin/badges': typeof AuthenticatedAdminBadgesRoute
  '/_authenticated/admin/banks': typeof AuthenticatedAdminBanksRouteWithChildren
  '/_authenticated/admin/challenges': typeof AuthenticatedAdminChallengesRoute
  '/_authenticated/admin/departments': typeof AuthenticatedAdminDepartmentsRoute
  '/_authenticated/admin/documents': typeof AuthenticatedAdminDocumentsRoute
  '/_authenticated/admin/items': typeof AuthenticatedAdminItemsRoute
  '/_authenticated/admin/members': typeof AuthenticatedAdminMembersRoute
  '/_authenticated/admin/upgrade': typeof AuthenticatedAdminUpgradeRoute
  '/_authenticated/host/$sessionId': typeof AuthenticatedHostSessionIdRoute
  '/_authenticated/invite/$token': typeof AuthenticatedInviteTokenRoute
  '/_authenticated/platform/billing': typeof AuthenticatedPlatformBillingRoute
  '/_authenticated/platform/health': typeof AuthenticatedPlatformHealthRoute
  '/_authenticated/platform/pipeline': typeof AuthenticatedPlatformPipelineRoute
  '/_authenticated/platform/settings': typeof AuthenticatedPlatformSettingsRoute
  '/_authenticated/platform/team': typeof AuthenticatedPlatformTeamRoute
  '/_authenticated/play/$sessionId': typeof AuthenticatedPlaySessionIdRoute
  '/_authenticated/quizzes/$id': typeof AuthenticatedQuizzesIdRoute
  '/_authenticated/results/$sessionId': typeof AuthenticatedResultsSessionIdRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/platform/': typeof AuthenticatedPlatformIndexRoute
  '/_authenticated/play/': typeof AuthenticatedPlayIndexRoute
  '/_authenticated/admin/banks/$bankId': typeof AuthenticatedAdminBanksBankIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/admin'
    | '/app'
    | '/challenges'
    | '/onboarding'
    | '/platform'
    | '/profile'
    | '/shop'
    | '/admin/analytics'
    | '/admin/badges'
    | '/admin/banks'
    | '/admin/challenges'
    | '/admin/departments'
    | '/admin/documents'
    | '/admin/items'
    | '/admin/members'
    | '/admin/upgrade'
    | '/host/$sessionId'
    | '/invite/$token'
    | '/platform/billing'
    | '/platform/health'
    | '/platform/pipeline'
    | '/platform/settings'
    | '/platform/team'
    | '/play/$sessionId'
    | '/quizzes/$id'
    | '/results/$sessionId'
    | '/admin/'
    | '/platform/'
    | '/play/'
    | '/admin/banks/$bankId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/app'
    | '/challenges'
    | '/onboarding'
    | '/profile'
    | '/shop'
    | '/admin/analytics'
    | '/admin/badges'
    | '/admin/banks'
    | '/admin/challenges'
    | '/admin/departments'
    | '/admin/documents'
    | '/admin/items'
    | '/admin/members'
    | '/admin/upgrade'
    | '/host/$sessionId'
    | '/invite/$token'
    | '/platform/billing'
    | '/platform/health'
    | '/platform/pipeline'
    | '/platform/settings'
    | '/platform/team'
    | '/play/$sessionId'
    | '/quizzes/$id'
    | '/results/$sessionId'
    | '/admin'
    | '/platform'
    | '/play'
    | '/admin/banks/$bankId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/admin'
    | '/_authenticated/app'
    | '/_authenticated/challenges'
    | '/_authenticated/onboarding'
    | '/_authenticated/platform'
    | '/_authenticated/profile'
    | '/_authenticated/shop'
    | '/_authenticated/admin/analytics'
    | '/_authenticated/admin/badges'
    | '/_authenticated/admin/banks'
    | '/_authenticated/admin/challenges'
    | '/_authenticated/admin/departments'
    | '/_authenticated/admin/documents'
    | '/_authenticated/admin/items'
    | '/_authenticated/admin/members'
    | '/_authenticated/admin/upgrade'
    | '/_authenticated/host/$sessionId'
    | '/_authenticated/invite/$token'
    | '/_authenticated/platform/billing'
    | '/_authenticated/platform/health'
    | '/_authenticated/platform/pipeline'
    | '/_authenticated/platform/settings'
    | '/_authenticated/platform/team'
    | '/_authenticated/play/$sessionId'
    | '/_authenticated/quizzes/$id'
    | '/_authenticated/results/$sessionId'
    | '/_authenticated/admin/'
    | '/_authenticated/platform/'
    | '/_authenticated/play/'
    | '/_authenticated/admin/banks/$bankId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/shop': {
      id: '/_authenticated/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof AuthenticatedShopRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/platform': {
      id: '/_authenticated/platform'
      path: '/platform'
      fullPath: '/platform'
      preLoaderRoute: typeof AuthenticatedPlatformRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/challenges': {
      id: '/_authenticated/challenges'
      path: '/challenges'
      fullPath: '/challenges'
      preLoaderRoute: typeof AuthenticatedChallengesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/play/': {
      id: '/_authenticated/play/'
      path: '/play'
      fullPath: '/play/'
      preLoaderRoute: typeof AuthenticatedPlayIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/platform/': {
      id: '/_authenticated/platform/'
      path: '/'
      fullPath: '/platform/'
      preLoaderRoute: typeof AuthenticatedPlatformIndexRouteImport
      parentRoute: typeof AuthenticatedPlatformRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/results/$sessionId': {
      id: '/_authenticated/results/$sessionId'
      path: '/results/$sessionId'
      fullPath: '/results/$sessionId'
      preLoaderRoute: typeof AuthenticatedResultsSessionIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/quizzes/$id': {
      id: '/_authenticated/quizzes/$id'
      path: '/quizzes/$id'
      fullPath: '/quizzes/$id'
      preLoaderRoute: typeof AuthenticatedQuizzesIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/play/$sessionId': {
      id: '/_authenticated/play/$sessionId'
      path: '/play/$sessionId'
      fullPath: '/play/$sessionId'
      preLoaderRoute: typeof AuthenticatedPlaySessionIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/platform/team': {
      id: '/_authenticated/platform/team'
      path: '/team'
      fullPath: '/platform/team'
      preLoaderRoute: typeof AuthenticatedPlatformTeamRouteImport
      parentRoute: typeof AuthenticatedPlatformRoute
    }
    '/_authenticated/platform/settings': {
      id: '/_authenticated/platform/settings'
      path: '/settings'
      fullPath: '/platform/settings'
      preLoaderRoute: typeof AuthenticatedPlatformSettingsRouteImport
      parentRoute: typeof AuthenticatedPlatformRoute
    }
    '/_authenticated/platform/pipeline': {
      id: '/_authenticated/platform/pipeline'
      path: '/pipeline'
      fullPath: '/platform/pipeline'
      preLoaderRoute: typeof AuthenticatedPlatformPipelineRouteImport
      parentRoute: typeof AuthenticatedPlatformRoute
    }
    '/_authenticated/platform/health': {
      id: '/_authenticated/platform/health'
      path: '/health'
      fullPath: '/platform/health'
      preLoaderRoute: typeof AuthenticatedPlatformHealthRouteImport
      parentRoute: typeof AuthenticatedPlatformRoute
    }
    '/_authenticated/platform/billing': {
      id: '/_authenticated/platform/billing'
      path: '/billing'
      fullPath: '/platform/billing'
      preLoaderRoute: typeof AuthenticatedPlatformBillingRouteImport
      parentRoute: typeof AuthenticatedPlatformRoute
    }
    '/_authenticated/invite/$token': {
      id: '/_authenticated/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof AuthenticatedInviteTokenRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/host/$sessionId': {
      id: '/_authenticated/host/$sessionId'
      path: '/host/$sessionId'
      fullPath: '/host/$sessionId'
      preLoaderRoute: typeof AuthenticatedHostSessionIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/upgrade': {
      id: '/_authenticated/admin/upgrade'
      path: '/upgrade'
      fullPath: '/admin/upgrade'
      preLoaderRoute: typeof AuthenticatedAdminUpgradeRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/members': {
      id: '/_authenticated/admin/members'
      path: '/members'
      fullPath: '/admin/members'
      preLoaderRoute: typeof AuthenticatedAdminMembersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/items': {
      id: '/_authenticated/admin/items'
      path: '/items'
      fullPath: '/admin/items'
      preLoaderRoute: typeof AuthenticatedAdminItemsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/documents': {
      id: '/_authenticated/admin/documents'
      path: '/documents'
      fullPath: '/admin/documents'
      preLoaderRoute: typeof AuthenticatedAdminDocumentsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/departments': {
      id: '/_authenticated/admin/departments'
      path: '/departments'
      fullPath: '/admin/departments'
      preLoaderRoute: typeof AuthenticatedAdminDepartmentsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/challenges': {
      id: '/_authenticated/admin/challenges'
      path: '/challenges'
      fullPath: '/admin/challenges'
      preLoaderRoute: typeof AuthenticatedAdminChallengesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/banks': {
      id: '/_authenticated/admin/banks'
      path: '/banks'
      fullPath: '/admin/banks'
      preLoaderRoute: typeof AuthenticatedAdminBanksRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/badges': {
      id: '/_authenticated/admin/badges'
      path: '/badges'
      fullPath: '/admin/badges'
      preLoaderRoute: typeof AuthenticatedAdminBadgesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/analytics': {
      id: '/_authenticated/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AuthenticatedAdminAnalyticsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/banks/$bankId': {
      id: '/_authenticated/admin/banks/$bankId'
      path: '/$bankId'
      fullPath: '/admin/banks/$bankId'
      preLoaderRoute: typeof AuthenticatedAdminBanksBankIdRouteImport
      parentRoute: typeof AuthenticatedAdminBanksRoute
    }
  }
}

interface AuthenticatedAdminBanksRouteChildren {
  AuthenticatedAdminBanksBankIdRoute: typeof AuthenticatedAdminBanksBankIdRoute
}

const AuthenticatedAdminBanksRouteChildren: AuthenticatedAdminBanksRouteChildren =
  {
    AuthenticatedAdminBanksBankIdRoute: AuthenticatedAdminBanksBankIdRoute,
  }

const AuthenticatedAdminBanksRouteWithChildren =
  AuthenticatedAdminBanksRoute._addFileChildren(
    AuthenticatedAdminBanksRouteChildren,
  )

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminAnalyticsRoute: typeof AuthenticatedAdminAnalyticsRoute
  AuthenticatedAdminBadgesRoute: typeof AuthenticatedAdminBadgesRoute
  AuthenticatedAdminBanksRoute: typeof AuthenticatedAdminBanksRouteWithChildren
  AuthenticatedAdminChallengesRoute: typeof AuthenticatedAdminChallengesRoute
  AuthenticatedAdminDepartmentsRoute: typeof AuthenticatedAdminDepartmentsRoute
  AuthenticatedAdminDocumentsRoute: typeof AuthenticatedAdminDocumentsRoute
  AuthenticatedAdminItemsRoute: typeof AuthenticatedAdminItemsRoute
  AuthenticatedAdminMembersRoute: typeof AuthenticatedAdminMembersRoute
  AuthenticatedAdminUpgradeRoute: typeof AuthenticatedAdminUpgradeRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminAnalyticsRoute: AuthenticatedAdminAnalyticsRoute,
  AuthenticatedAdminBadgesRoute: AuthenticatedAdminBadgesRoute,
  AuthenticatedAdminBanksRoute: AuthenticatedAdminBanksRouteWithChildren,
  AuthenticatedAdminChallengesRoute: AuthenticatedAdminChallengesRoute,
  AuthenticatedAdminDepartmentsRoute: AuthenticatedAdminDepartmentsRoute,
  AuthenticatedAdminDocumentsRoute: AuthenticatedAdminDocumentsRoute,
  AuthenticatedAdminItemsRoute: AuthenticatedAdminItemsRoute,
  AuthenticatedAdminMembersRoute: AuthenticatedAdminMembersRoute,
  AuthenticatedAdminUpgradeRoute: AuthenticatedAdminUpgradeRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedPlatformRouteChildren {
  AuthenticatedPlatformBillingRoute: typeof AuthenticatedPlatformBillingRoute
  AuthenticatedPlatformHealthRoute: typeof AuthenticatedPlatformHealthRoute
  AuthenticatedPlatformPipelineRoute: typeof AuthenticatedPlatformPipelineRoute
  AuthenticatedPlatformSettingsRoute: typeof AuthenticatedPlatformSettingsRoute
  AuthenticatedPlatformTeamRoute: typeof AuthenticatedPlatformTeamRoute
  AuthenticatedPlatformIndexRoute: typeof AuthenticatedPlatformIndexRoute
}

const AuthenticatedPlatformRouteChildren: AuthenticatedPlatformRouteChildren = {
  AuthenticatedPlatformBillingRoute: AuthenticatedPlatformBillingRoute,
  AuthenticatedPlatformHealthRoute: AuthenticatedPlatformHealthRoute,
  AuthenticatedPlatformPipelineRoute: AuthenticatedPlatformPipelineRoute,
  AuthenticatedPlatformSettingsRoute: AuthenticatedPlatformSettingsRoute,
  AuthenticatedPlatformTeamRoute: AuthenticatedPlatformTeamRoute,
  AuthenticatedPlatformIndexRoute: AuthenticatedPlatformIndexRoute,
}

const AuthenticatedPlatformRouteWithChildren =
  AuthenticatedPlatformRoute._addFileChildren(
    AuthenticatedPlatformRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedAppRoute: typeof AuthenticatedAppRoute
  AuthenticatedChallengesRoute: typeof AuthenticatedChallengesRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedPlatformRoute: typeof AuthenticatedPlatformRouteWithChildren
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedShopRoute: typeof AuthenticatedShopRoute
  AuthenticatedHostSessionIdRoute: typeof AuthenticatedHostSessionIdRoute
  AuthenticatedInviteTokenRoute: typeof AuthenticatedInviteTokenRoute
  AuthenticatedPlaySessionIdRoute: typeof AuthenticatedPlaySessionIdRoute
  AuthenticatedQuizzesIdRoute: typeof AuthenticatedQuizzesIdRoute
  AuthenticatedResultsSessionIdRoute: typeof AuthenticatedResultsSessionIdRoute
  AuthenticatedPlayIndexRoute: typeof AuthenticatedPlayIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedAppRoute: AuthenticatedAppRoute,
  AuthenticatedChallengesRoute: AuthenticatedChallengesRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedPlatformRoute: AuthenticatedPlatformRouteWithChildren,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedShopRoute: AuthenticatedShopRoute,
  AuthenticatedHostSessionIdRoute: AuthenticatedHostSessionIdRoute,
  AuthenticatedInviteTokenRoute: AuthenticatedInviteTokenRoute,
  AuthenticatedPlaySessionIdRoute: AuthenticatedPlaySessionIdRoute,
  AuthenticatedQuizzesIdRoute: AuthenticatedQuizzesIdRoute,
  AuthenticatedResultsSessionIdRoute: AuthenticatedResultsSessionIdRoute,
  AuthenticatedPlayIndexRoute: AuthenticatedPlayIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
